
name: Weekly Action Tests

on:
  workflow_dispatch:
  schedule:
    - cron: 0 15 * * 1

permissions:
  contents: read

jobs:
  test_sarif_flow:
    runs-on: ubuntu-latest    
    permissions:
      security-events: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Scan model on HuggingFace
        id: scan_model_huggingface
        uses: hiddenlayerai/hiddenlayer-model-scan-github-action@main
        with:
          model_path: hf://drhyrum/bert-tiny-torch-vuln
          fail_on_detection: false
          output_file: output.json
          sarif_file: output.sarif
        env:
          HL_CLIENT_ID: ${{ secrets.HL_CLIENT_ID }}
          HL_CLIENT_SECRET: ${{ secrets.HL_CLIENT_SECRET }}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@f6091c0113d1dcf9b98e269ee48e8a7e51b7bdd4 # v3.28.5
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: output.sarif
