
name: Weekly Action Tests

on:
  workflow_dispatch:
  schedule:
    - cron: 0 15 * * 1
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test_sarif_flow:
    runs-on: ubuntu-latest    
    permissions:
      security-events: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Scan model on HuggingFace
        id: scan_model_huggingface
        uses: ./ # Testing the action from this repository
        with:
          model_path: hf://drhyrum/bert-tiny-torch-vuln
          fail_on_detection: false
          output_file: output.json
          sarif_file: output.sarif
        env:
          HL_CLIENT_ID: ${{ secrets.HL_CLIENT_ID }}
          HL_CLIENT_SECRET: ${{ secrets.HL_CLIENT_SECRET }}
      - name: Community Scan Hugging HuggingFace
        id: community_scan_huggingface
        uses: ./ # Testing the action from this repository
        with:
          model_path: https://HuggingFace.co/ScanMe/Models
          fail_on_detection: false
          output_file: output.json
          sarif_file: output.sarif
          community_scan: 'HUGGING_FACE'
        env:
          HL_CLIENT_ID: ${{ secrets.HL_CLIENT_ID }}
          HL_CLIENT_SECRET: ${{ secrets.HL_CLIENT_SECRET }}
      - name: Upload Scan SARIF File as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: community-scan.sarif
          path: output.sarif
      - name: Upload Community Scan SARIF file
        uses: github/codeql-action/upload-sarif@6bb031afdd8eb862ea3fc1848194185e076637e5 # v3.28.11
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: output.sarif
