
name: Weekly Action Tests

on:
  workflow_dispatch:
  schedule:
    - cron: 0 15 * * 1
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test_sarif_flow:
    runs-on: ubuntu-latest    
    permissions:
      security-events: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Scan model on HuggingFace
        id: scan_model_huggingface
        uses: ./ # Testing the action from this repository
        with:
          model_path: hf://drhyrum/bert-tiny-torch-vuln
          fail_on_detection: false
          output_file: output.json
          sarif_file: output.sarif
        env:
          HL_CLIENT_ID: ${{ secrets.HL_CLIENT_ID }}
          HL_CLIENT_SECRET: ${{ secrets.HL_CLIENT_SECRET }}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@9e8d0789d4a0fa9ceb6b1738f7e269594bdd67f0 # v3.28.9
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: output.sarif
