
name: Weekly Action Tests

on:
  workflow_dispatch:
  schedule:
    - cron: 0 15 * * 1
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test_sarif_flow:
    runs-on: ubuntu-latest    
    permissions:
      security-events: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Scan model on HuggingFace
        id: scan_model_huggingface
        uses: ./ # Testing the action from this repository
        with:
          model_path: hf://drhyrum/bert-tiny-torch-vuln
          fail_on_detection: false
          output_file: output.json
          sarif_file: output.sarif
        env:
          HL_CLIENT_ID: ${{ secrets.HL_CLIENT_ID }}
          HL_CLIENT_SECRET: ${{ secrets.HL_CLIENT_SECRET }}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@b56ba49b26e50535fa1e7f7db0f4f7b4bf65d80d # v3.28.10
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: output.sarif
